//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.My
{
    [Serializable]
    public class SceneObjectsMsg : Message
    {
        public const string k_RosMessageName = "my_msgs/SceneObjects";
        public override string RosMessageName => k_RosMessageName;

        public string[] ids;

        public SceneObjectsMsg()
        {
            this.ids = new string[0];
        }

        public SceneObjectsMsg(string[] ids)
        {
            this.ids = ids;
        }

        public static SceneObjectsMsg Deserialize(MessageDeserializer deserializer) => new SceneObjectsMsg(deserializer);

        private SceneObjectsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ids, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.ids);
            serializer.Write(this.ids);
        }

        public override string ToString()
        {
            return "SceneObjectsMsg: " +
            "\nids: " + System.String.Join(", ", ids.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
